- name: Deploy Brand BE service
  hosts: all
  gather_facts: yes
  vars:
    timestamp: "{{ ansible_date_time.epoch }}"
  tasks:
    - name: Deployment block
      block:
        - name: Create deployment folder
          file:
            path: ~/deploy-{{ timestamp }}
            state: directory

        - name: Clone deployment repo
          git:
            repo: 'https://github.com/mocchi-app/mocchi-deployment.git'
            dest: ~/deploy-{{ timestamp }}

        - name: Start up application
          docker_compose:
            project_src: ~/deploy-{{ timestamp }}
            project_name: mocchi
            services: brand-fe
            state: present
            pull: yes
            restarted: true

      always:
        - name: Remove deployment folder
          file:
            path: ~/deploy-{{ timestamp }}
            state: absent
