name: Build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2

      - name: npm install
        run: npm install

      - name: Build app
        run: npm run build

      - name: Build the Docker image
        run: docker login docker.pkg.github.com -u sausageRoll -p ${{ secrets.GITHUB_TOKEN }} && docker build . --file Dockerfile --tag docker.pkg.github.com/mocchi-app/brand-fe/brand-fe:latest
      - name: Publish the Docker image
        run: docker push docker.pkg.github.com/mocchi-app/brand-fe/brand-fe:latest

